
Pool_Update_Rate_ms = 1000
LoopParticlesNetworkDistance2D = 25000
TemporaryParticlesNetworkDistance2D = 25000


particlespakfiles = {
    "particles1",
    "particles2",
    "particles3",
    "particles4"
}


TemporaryParticles = {
    "/Game/Vehicle/VFX/Heli_RotorSparks",
    "/Game/Vehicle/VFX/Heli_Wake_Effect",
    "/Game/Vehicle/VFX/P_DamageSparks",
    "/Game/Vehicle/VFX/Effects/Particles/P_Exhaust_Backfire",
    "/Game/Scripting/Fireworks/Particles/PS_TS_Fireworks_Burst_Chrys",
    "/Game/Scripting/Fireworks/Particles/PS_TS_Fireworks_Burst_Circle",
    "/Game/Scripting/Fireworks/Particles/PS_TS_Fireworks_Burst_Palm",
    "/Game/Scripting/Fireworks/Particles/PS_TS_Fireworks_Burst_Shaped",
    "/Game/Scripting/Fireworks/Particles/PS_TS_Fireworks_ShellsWithinShells",
    "/Game/Character/Particles/PS_Splash",
    "/Game/Explosions/Particles/P_BPExplosion1",
    "/Game/Explosions/Particles/P_BPExplosion2",
    "/Game/Explosions/Particles/P_BPExplosion3",
    "/Game/Explosions/Particles/P_BPExplosion4",
    "/Game/Explosions/Particles/P_BPExplosion5",
    "/Game/Explosions/Particles/P_BPExplosion6",
    "/Game/Explosions/Particles/P_BPExplosion7",
    "/Game/Explosions/Particles/P_BPExplosion8",
    "/Game/Explosions/Particles/P_BPExplosion9",
    "/Game/Explosions/Particles/P_BPExplosion10",
    "/Game/Explosions/Particles/P_BPExplosion11",
    "/Game/Explosions/Particles/P_BPExplosion12",
    "/Game/Explosions/Particles/P_BPExplosion13",
    "/Game/Explosions/Particles/P_BPExplosion14",
    "/Game/Explosions/Particles/P_BPExplosion15",
    "/Game/Explosions/Particles/P_BPExplosion16",
    "/Game/Explosions/Particles/P_BPExplosion17",
    "/Game/Explosions/Particles/P_BPExplosion18",
    "/Game/Explosions/Particles/P_BPExplosion19",
    "/Game/Explosions/Particles/P_BPExplosion20",
    "/Game/Explosions/Particles/P_Explode2",
    "/Game/Weapons/VFX/Impacts/Particles/P_ImpactBlood",
    "/Game/Weapons/VFX/Impacts/Particles/P_ImpactBloodCloud",
    "/Game/Weapons/VFX/Impacts/Particles/P_ImpactDirt",
    "/Game/Weapons/VFX/Impacts/Particles/P_ImpactGrass",
    "/Game/Weapons/VFX/Impacts/Particles/P_ImpactMetal",
    "/Game/Weapons/VFX/Impacts/Particles/P_ImpactPlaster",
    "/Game/Weapons/VFX/Impacts/Particles/P_ImpactSand",
    "/Game/Weapons/VFX/Impacts/Particles/P_ImpactSheetrock",
    "/Game/Weapons/VFX/Impacts/Particles/P_ImpactTile",
    "/Game/Weapons/VFX/Impacts/Particles/P_ImpactWater",
    "/Game/Weapons/VFX/Impacts/Particles/P_ShellSmoke",
    "/Game/Weapons/VFX/Particles/Shells/P_AR_Shell",
    "/Game/Weapons/VFX/Particles/Shells/P_SG_Shell",
    "/Game/Weapons/VFX/Particles/Shells/P_Shell",
    "/Game/Weapons/VFX/Particles/Shells/P_PM_Shell",
    "/Game/Weapons/VFX/Particles/Weapons/PS_L96",
    "/Game/Weapons/VFX/Particles/Weapons/PS_M4A1",
    "/Game/Weapons/VFX/Particles/Weapons/PS_Pistol",
    "/Game/Weapons/VFX/Particles/Weapons/PS_Pistol01",
    "/Game/Weapons/VFX/Particles/Weapons/PS_Rifle02",
    "/Game/Weapons/VFX/Particles/Weapons/PS_Rifle03",
    "/Game/Weapons/VFX/Particles/Weapons/PS_Rifle04",
    "/Game/Weapons/VFX/Particles/Weapons/PS_Shotgun01",
    "/Game/Weapons/VFX/Particles/Weapons/PS_Shotgun02",
    "/Game/Weapons/VFX/Particles/Weapons/PS_SMG01",
    "/Game/Weapons/VFX/Particles/Weapons/PS_SMG02",
    "/Game/Weapons/VFX/Particles/Weapons/PS_Taser",

    "/particles1/AdvancedMagicFX12/particles/P_ky_hit",
    "/particles1/AdvancedMagicFX12/particles/P_ky_hit_dark",
    "/particles1/AdvancedMagicFX12/particles/P_ky_hit_fire",
    "/particles1/AdvancedMagicFX12/particles/P_ky_hit_ice",
    "/particles1/AdvancedMagicFX12/particles/P_ky_hit_shine",
    "/particles1/AdvancedMagicFX12/particles/P_ky_hit_thunder",
    "/particles1/AdvancedMagicFX12/particles/P_ky_hit_water",

    "/particles2/AdvancedMagicFX13/Particles/P_ky_burst",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_burstBall1",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_burstBall2",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_cross",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_explosion1",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_explosion2",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_explosion3",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_flash1",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_flash2",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_gaither",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_heal1",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_heal2",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_hit_slash",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_impact",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_stab",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_stabShot2",

    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_ArrowRain_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_BombWaker",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_BuffRing_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_BurstArrow_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Carotia",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_CrescentBoom3",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_CrystalPop_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_DiamondSpawn",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_DivineLaser",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_FightCloud_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_FlashRing",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_FlowerBulb",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_HealLeaf_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_HealTrineFX_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_HexaField",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_KineticForce_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_LuCoins",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_LuGhost_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_MatraBoom_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Meteora_Explode_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_MissileExplosion",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_MuzzleFlash1_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_RainBlow_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_RainBlowSparks_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Shurricane_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_SwirlBeamBoom",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_SwoSweeps_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Thundara_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_ToonBoom2",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_ToonKaboom_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_TriBlaster",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Vortexian",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_VulcaBoom_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Vulcannon_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_WarpBall_01",
}

LoopParticles = {
    "/Game/Explosions/Particles/P_LoopingFire1c_MV", -- 1
    "/Game/Explosions/Particles/P_LoopingFlame1d_MV",
    "/Game/Explosions/Particles/P_LoopingFlame3b_MV",
    "/Game/Explosions/Particles/P_LoopingSmoke1_MV",
    "/Game/Vehicle/VFX/Effects/Particles/P_Wheel_Dirt", -- 5
    "/Game/Vehicle/VFX/Effects/Particles/P_Wheel_Dust",
    "/Game/Vehicle/VFX/Effects/Particles/P_Wheel_Leaf",
    "/Game/Vehicle/VFX/Effects/Particles/P_Wheel_Water",
    "/Game/Vehicle/VFX/Effects/Particles/P_Wheel_Wood",
    "/Game/Vehicle/VFX/PS_VehicleExhaustSmoke", -- 10
    "/Game/Vehicle/VFX/PS_VehicleSmoke",
    "/Game/Vehicle/VFX/Fire/2_bonefire2_pt",
    "/Game/Vehicle/VFX/Fire/2_bonefire2B_fwd2_pt",
    "/Game/Vehicle/VFX/Fire/2_bonefire2B_fwd_pt",
    "/Game/Vehicle/VFX/Fire/2_bonefire3_pt", -- 15
    "/Game/Vehicle/VFX/Fire/2_bonefire4_pt",
    "/Game/Vehicle/VFX/Fire/2_bonefire_pt",
    "/Game/Vehicle/VFX/Fire/2_bonefirethin_pt",
    "/Game/Vehicle/VFX/TireSmoke/Particles/P_SmokePuff",
    "/Game/Vehicle/VFX/TireSmoke/Particles/P_SmokePuffDirt", -- 20
    "/Game/Vehicle/VFX/PS_DistortHigh",
    "/Game/Vehicle/VFX/PS_DistortLow",
    "/Game/Vehicle/VFX/PS_DistortMid",
    "/Game/Scripting/Fireworks/Particles/PS_TS_FireworksShell",
    "/Game/Weapons/VFX/Particles/Weapons/PS_MuzzleFlash12", -- 25
    "/Game/Explosions/Particles/P_Fireball5_MV2",
    "/Game/Vehicle/VFX/PS_VehicleExhaustSmokeStill",
    "/Game/Vehicle/VFX/PS_VehicleSmokeFire",
    "/Game/Scripting/Effects/Particles/Snow/P_SnowFlare",
    "/Game/Vehicle/VFX/P_Nitro", -- 30
    "/Game/Scripting/Fireworks/Particles/PS_TS_FireworksShell_Palm",
    "/Game/Vehicle/VFX/Effects/Particles/P_Exhaust",
    "/Game/Geometry/OldTown/Effects/PS_LanternFire",

    "/particles1/AdvancedMagicFX12/particles/P_ky_aura",
    "/particles1/AdvancedMagicFX12/particles/P_ky_aura_dark", -- 35
    "/particles1/AdvancedMagicFX12/particles/P_ky_aura_fire",
    "/particles1/AdvancedMagicFX12/particles/P_ky_aura_ice",
    "/particles1/AdvancedMagicFX12/particles/P_ky_aura_shine",
    "/particles1/AdvancedMagicFX12/particles/P_ky_aura_thunder",
    "/particles1/AdvancedMagicFX12/particles/P_ky_aura_water", -- 40
    "/particles1/AdvancedMagicFX12/particles/P_ky_shot",
    "/particles1/AdvancedMagicFX12/particles/P_ky_shot_dark",
    "/particles1/AdvancedMagicFX12/particles/P_ky_shot_fire",
    "/particles1/AdvancedMagicFX12/particles/P_ky_shot_ice",
    "/particles1/AdvancedMagicFX12/particles/P_ky_shot_shine", -- 45
    "/particles1/AdvancedMagicFX12/particles/P_ky_shot_thunder",
    "/particles1/AdvancedMagicFX12/particles/P_ky_shot_water",

    "/particles2/AdvancedMagicFX13/Particles/P_ky_aquaStorm",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_auroraAura",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_cutter1", -- 50
    "/particles2/AdvancedMagicFX13/Particles/P_ky_cutter2",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_fireStorm",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_stabShot",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_storm",
    "/particles2/AdvancedMagicFX13/Particles/P_ky_thunderStorm", -- 55

    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_BubblePop_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_CrescentBoom2_OLD",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_CrescentBoom_OLD",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_DustParticles_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Galaxoid_01", -- 60
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Kaiser_Shot_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Kaiser_Shot_01a",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_LitClouds_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Matra_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Matra_01b_Trail", -- 65
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Meteora_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_MissileTrails",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_MissileTrails2",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_MuzzleFlash1_02",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Paralexia_01", -- 70
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_PlasmaBall_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_PlasmaBall_02",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_RainBlowSparks_02",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Skybirds_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_SparCore_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_SwoSweep2_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Thisle_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_TorchFire_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_VecFielder_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_VoltCore_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Voya_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Voya_Sparks_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_WhirlCopterRibbon",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_WildImpact_01",
    "/particles3/VFX_Toolkit_V1/ParticleSystems/356Days/Par_Windia_System_1",

    "/particles4/Particles_Wind_Control_System/Particles/P_Candle_Fire_Particle",
    "/particles4/Particles_Wind_Control_System/Particles/P_Dandelion",
    "/particles4/Particles_Wind_Control_System/Particles/P_Fireflies",
    "/particles4/Particles_Wind_Control_System/Particles/P_Leaves",
    "/particles4/Particles_Wind_Control_System/Particles/P_Smoke",
    "/particles4/Particles_Wind_Control_System/Particles/P_Snow",
}